"""PyExporter Module

This module provides functionality to export UPPAAL models to Python code format.
"""

from __future__ import annotations
import os
import re
import keyword
from typing import List, Dict, Tuple, Literal, TYPE_CHECKING

if TYPE_CHECKING:
    from .umodel import UModel
    from .nta import Template, Location, Edge

# Reserved directory names that cannot be used as template names
RESERVED_NAMES = frozenset({
    "decl", "sys_decl", "queries", "__pycache__", "templates"
})

# Valid template name pattern: must be a valid Python identifier
VALID_NAME_PATTERN = re.compile(r'^[A-Za-z_][A-Za-z0-9_]*$')


class PyExporter:
    """Stateless Python format exporter class.

    Exports UModel to Python code format folder structure.
    All methods are static methods, the class itself does not save any state.
    """

    @staticmethod
    def export(
        umodel: "UModel",
        output_dir: str,
        mode: Literal["human", "machine"] = "human",
        overwrite: bool = False
    ) -> None:
        """Main export interface.

        Args:
            umodel: The UModel instance to export.
            output_dir: Output directory path.
            mode: Export mode - "human" for Python code, "machine" for TOML data.
            overwrite: If False, raises error when output_dir is non-empty.

        Raises:
            ValueError: If template names are invalid or output_dir is non-empty
                       when overwrite=False.

        Generated directory structure (human mode):
            output_dir/
            ├── __init__.py
            ├── decl/
            │   ├── __init__.py
            │   └── decl.txt
            ├── sys_decl/
            │   ├── __init__.py
            │   └── sys_decl.txt
            ├── queries/
            │   ├── __init__.py
            │   └── queries.py
            ├── {TemplateName}/
            │   ├── __init__.py
            │   ├── decl_{TemplateName}.txt
            │   └── template_{TemplateName}.py
            └── registry.py

        Generated directory structure (machine mode):
            output_dir/
            ├── manifest.toml
            ├── decl/
            │   └── decl.toml
            ├── sys_decl/
            │   └── sys_decl.toml
            ├── queries/
            │   └── queries.toml
            └── {TemplateName}/
                └── {TemplateName}.toml
        """
        # Validate template names
        PyExporter._validate_template_names(umodel.templates)

        # Check output directory
        if os.path.exists(output_dir) and os.listdir(output_dir):
            if not overwrite:
                raise ValueError(
                    f"Output directory '{output_dir}' is not empty. "
                    f"Use overwrite=True to overwrite existing files."
                )

        # Create output directory if not exists
        os.makedirs(output_dir, exist_ok=True)

        if mode == "human":
            PyExporter._export_human_mode(umodel, output_dir)
        else:
            PyExporter._export_machine_mode(umodel, output_dir)

    @staticmethod
    def _export_human_mode(umodel: "UModel", output_dir: str) -> None:
        """Export in human mode (Python code format).

        Args:
            umodel: The UModel instance to export.
            output_dir: Output directory path.
        """
        # Create root __init__.py
        PyExporter._write_init_py(output_dir)

        # Export global declaration
        PyExporter._export_global_declaration(umodel.declaration, output_dir)

        # Export system declaration
        PyExporter._export_system_declaration(umodel.system, output_dir)

        # Export queries
        PyExporter._export_queries(umodel.queries, output_dir)

        # Export each template (using Template.name directly)
        for template in umodel.templates:
            PyExporter._export_template(template, output_dir)

        # Generate registry.py
        PyExporter._export_registry(umodel.templates, output_dir)

    @staticmethod
    def _write_init_py(dir_path: str, content: str = "") -> None:
        """Write __init__.py file to directory.

        Args:
            dir_path: Directory path.
            content: Optional content for __init__.py.
        """
        init_path = os.path.join(dir_path, "__init__.py")
        header = "# Auto-generated by PyUPPAAL PyExporter\n"
        with open(init_path, "w", encoding="utf-8") as f:
            f.write(header + content)

    @staticmethod
    def _export_global_declaration(declaration: str, output_dir: str) -> None:
        """Export global declaration to decl/decl.txt.

        Args:
            declaration: Global declaration content.
            output_dir: Output directory path.
        """
        decl_dir = os.path.join(output_dir, "decl")
        os.makedirs(decl_dir, exist_ok=True)

        # Write __init__.py
        PyExporter._write_init_py(decl_dir)

        # Write declaration file
        decl_path = os.path.join(decl_dir, "decl.txt")
        with open(decl_path, "w", encoding="utf-8") as f:
            f.write(declaration if declaration else "")

    @staticmethod
    def _export_system_declaration(system: str, output_dir: str) -> None:
        """Export system declaration to sys_decl/sys_decl.txt.

        Args:
            system: System declaration content.
            output_dir: Output directory path.
        """
        sys_decl_dir = os.path.join(output_dir, "sys_decl")
        os.makedirs(sys_decl_dir, exist_ok=True)

        # Write __init__.py
        PyExporter._write_init_py(sys_decl_dir)

        # Write system declaration file
        sys_decl_path = os.path.join(sys_decl_dir, "sys_decl.txt")
        with open(sys_decl_path, "w", encoding="utf-8") as f:
            f.write(system if system else "")

    @staticmethod
    def _export_queries(queries: List[str], output_dir: str) -> None:
        """Export queries to queries/queries.py.

        Args:
            queries: List of query strings.
            output_dir: Output directory path.
        """
        queries_dir = os.path.join(output_dir, "queries")
        os.makedirs(queries_dir, exist_ok=True)

        # Write __init__.py with import
        init_content = "from .queries import QUERIES\n"
        PyExporter._write_init_py(queries_dir, init_content)

        # Generate queries.py content
        lines = [
            "# queries.py",
            "# Auto-generated by PyUPPAAL PyExporter",
            "",
            "QUERIES = [",
        ]

        if queries:
            for query in queries:
                if query is None:
                    continue
                # Use triple quotes for multiline strings
                escaped_query = PyExporter._escape_triple_quote_string(query)
                lines.append(f'    """{escaped_query}""",')

        lines.append("]")
        lines.append("")

        queries_path = os.path.join(queries_dir, "queries.py")
        with open(queries_path, "w", encoding="utf-8") as f:
            f.write("\n".join(lines))

    @staticmethod
    def _export_template(template: "Template", output_dir: str) -> None:
        """Export a single Template to its subfolder.

        Args:
            template: Template instance to export.
            output_dir: Output directory path.
        """
        # Use template name directly (validation ensures it's a valid identifier)
        name = template.name

        template_dir = os.path.join(output_dir, name)
        os.makedirs(template_dir, exist_ok=True)

        # Write __init__.py with import
        init_content = f"from .template_{name} import template_{name}\n"
        PyExporter._write_init_py(template_dir, init_content)

        # Write template local declaration
        decl_path = os.path.join(template_dir, f"decl_{name}.txt")
        with open(decl_path, "w", encoding="utf-8") as f:
            f.write(template.declaration if template.declaration else "")

        # Generate and write template Python code
        template_code = PyExporter._generate_template_py_code(template, name)
        template_path = os.path.join(template_dir, f"template_{name}.py")
        with open(template_path, "w", encoding="utf-8") as f:
            f.write(template_code)

    @staticmethod
    def _generate_template_py_code(template: "Template", safe_name: str) -> str:
        """Generate Python code string for a Template.

        Args:
            template: Template instance.
            safe_name: Safe Python identifier for the template name.

        Returns:
            Python code string.
        """
        original_name = template.name

        # Build location_id to location_pos mapping for edge position inference
        loc_id_to_pos: Dict[int, Tuple[int, int]] = {}
        for loc in template.locations:
            loc_id_to_pos[loc.location_id] = loc.location_pos

        # Mark initial location
        init_location_id = template.init_ref

        lines = [
            f"# template_{safe_name}.py",
            "# Auto-generated by PyUPPAAL PyExporter",
            "",
            "import os",
            "from pyuppaal.nta import Template, Location, Edge",
            "",
            "# Get current file directory",
            "_CURRENT_DIR = os.path.dirname(os.path.abspath(__file__))",
            "",
            "",
            "def load_declaration() -> str:",
            '    """Load Template local declaration."""',
            f'    decl_path = os.path.join(_CURRENT_DIR, "decl_{safe_name}.txt")',
            '    with open(decl_path, "r", encoding="utf-8") as f:',
            "        return f.read()",
            "",
            "",
            "# " + "=" * 60,
            f"# Template: {original_name}",
            "# " + "=" * 60,
            "",
        ]

        # Generate location code
        lines.append("# " + "-" * 60)
        lines.append("# Locations")
        lines.append("# " + "-" * 60)
        lines.append("")

        location_var_names = []
        for i, loc in enumerate(template.locations):
            var_name = f"l{i}"
            location_var_names.append(var_name)
            # Check if this is the initial location
            is_initial = (loc.location_id == init_location_id)
            loc_code = PyExporter._generate_location_py_code(loc, var_name, is_initial)
            lines.append(loc_code)
            lines.append("")

        # Generate edge code
        lines.append("# " + "-" * 60)
        lines.append("# Edges")
        lines.append("# " + "-" * 60)
        lines.append("")

        edge_var_names = []
        if template.edges:
            for i, edge in enumerate(template.edges):
                var_name = f"e{i}"
                edge_var_names.append(var_name)
                edge_code = PyExporter._generate_edge_py_code(edge, var_name, loc_id_to_pos)
                lines.append(edge_code)
                lines.append("")

        # Generate template instantiation
        lines.append("# " + "-" * 60)
        lines.append("# Template instantiation")
        lines.append("# " + "-" * 60)
        lines.append("")

        # Build template instantiation code
        template_lines = [
            f"template_{safe_name} = Template(",
            f'    name="{original_name}",',
            f"    locations=[{', '.join(location_var_names)}],",
            f"    init_ref={init_location_id},",
        ]

        if edge_var_names:
            template_lines.append(f"    edges=[{', '.join(edge_var_names)}],")
        else:
            template_lines.append("    edges=[],")

        if template.params:
            escaped_params = PyExporter._escape_string(template.params)
            template_lines.append(f'    params="{escaped_params}",')

        template_lines.append("    declaration=load_declaration()")
        template_lines.append(")")
        template_lines.append("")

        lines.extend(template_lines)

        return "\n".join(lines)

    @staticmethod
    def _generate_location_py_code(location: "Location", var_name: str, is_initial: bool = False) -> str:
        """Generate Python code string for a single Location.

        Args:
            location: Location instance.
            var_name: Variable name for the location.
            is_initial: Whether this location is the initial location.

        Returns:
            Python code string.
        """
        lines = [f"{var_name} = Location("]
        lines.append(f"    location_id={location.location_id},")
        lines.append(f"    location_pos={PyExporter._format_tuple(location.location_pos)},")

        if location.name is not None:
            lines.append(f'    name="{PyExporter._escape_string(location.name)}",')

        if location.name_pos is not None:
            lines.append(f"    name_pos={PyExporter._format_tuple(location.name_pos)},")

        if location.invariant is not None:
            lines.append(f'    invariant="{PyExporter._escape_string(location.invariant)}",')

        if location.invariant_pos is not None:
            lines.append(f"    invariant_pos={PyExporter._format_tuple(location.invariant_pos)},")

        if location.rate_of_exponential is not None:
            lines.append(f"    rate_of_exponential={location.rate_of_exponential},")

        if location.rate_of_exp_pos is not None:
            lines.append(f"    rate_of_exp_pos={PyExporter._format_tuple(location.rate_of_exp_pos)},")

        # Use the passed is_initial parameter (based on init_ref) instead of location.is_initial
        if is_initial:
            lines.append("    is_initial=True,")

        if location.is_urgent:
            lines.append("    is_urgent=True,")

        if location.is_committed:
            lines.append("    is_committed=True,")

        if location.is_branchpoint:
            lines.append("    is_branchpoint=True,")

        if location.comments is not None:
            escaped = PyExporter._escape_string(location.comments)
            lines.append(f'    comments="{escaped}",')

        if location.comments_pos is not None:
            lines.append(f"    comments_pos={PyExporter._format_tuple(location.comments_pos)},")

        if location.test_code_on_enter is not None:
            escaped = PyExporter._escape_string(location.test_code_on_enter)
            lines.append(f'    test_code_on_enter="{escaped}",')

        if location.test_code_on_exit is not None:
            escaped = PyExporter._escape_string(location.test_code_on_exit)
            lines.append(f'    test_code_on_exit="{escaped}",')

        lines.append(")")

        return "\n".join(lines)

    @staticmethod
    def _generate_edge_py_code(edge: "Edge", var_name: str, loc_id_to_pos: Dict[int, Tuple[int, int]]) -> str:
        """Generate Python code string for a single Edge.

        Args:
            edge: Edge instance.
            var_name: Variable name for the edge.
            loc_id_to_pos: Mapping from location_id to location_pos for position normalization.

        Returns:
            Python code string.
        """
        # Normalize source/target positions to location positions (always use location pos)
        source_pos = loc_id_to_pos.get(edge.source_location_id, edge.source_location_pos)
        target_pos = loc_id_to_pos.get(edge.target_location_id, edge.target_location_pos)

        lines = [f"{var_name} = Edge("]
        lines.append(f"    source_location_id={edge.source_location_id},")
        lines.append(f"    target_location_id={edge.target_location_id},")
        lines.append(f"    source_location_pos={PyExporter._format_tuple(source_pos)},")
        lines.append(f"    target_location_pos={PyExporter._format_tuple(target_pos)},")

        if edge.select is not None:
            lines.append(f'    select="{PyExporter._escape_string(edge.select)}",')

        if edge.select_pos is not None:
            lines.append(f"    select_pos={PyExporter._format_tuple(edge.select_pos)},")

        if edge.sync is not None:
            lines.append(f'    sync="{PyExporter._escape_string(edge.sync)}",')

        if edge.sync_pos is not None:
            lines.append(f"    sync_pos={PyExporter._format_tuple(edge.sync_pos)},")

        if edge.update is not None:
            lines.append(f'    update="{PyExporter._escape_string(edge.update)}",')

        if edge.update_pos is not None:
            lines.append(f"    update_pos={PyExporter._format_tuple(edge.update_pos)},")

        if edge.guard is not None:
            lines.append(f'    guard="{PyExporter._escape_string(edge.guard)}",')

        if edge.guard_pos is not None:
            lines.append(f"    guard_pos={PyExporter._format_tuple(edge.guard_pos)},")

        if edge.probability_weight is not None:
            lines.append(f"    probability_weight={edge.probability_weight},")

        if edge.prob_weight_pos is not None:
            lines.append(f"    prob_weight_pos={PyExporter._format_tuple(edge.prob_weight_pos)},")

        if edge.comments is not None:
            escaped = PyExporter._escape_string(edge.comments)
            lines.append(f'    comments="{escaped}",')

        if edge.comments_pos is not None:
            lines.append(f"    comments_pos={PyExporter._format_tuple(edge.comments_pos)},")

        if edge.test_code is not None:
            escaped = PyExporter._escape_string(edge.test_code)
            lines.append(f'    test_code="{escaped}",')

        if edge.nails:
            nails_str = "[" + ", ".join(PyExporter._format_tuple(n) for n in edge.nails) + "]"
            lines.append(f"    nails={nails_str},")

        lines.append(")")

        return "\n".join(lines)

    @staticmethod
    def _export_registry(templates: List["Template"], output_dir: str) -> None:
        """Generate registry.py.

        Args:
            templates: List of Template instances.
            output_dir: Output directory path.
        """
        lines = [
            "# registry.py",
            "# Auto-generated by PyUPPAAL PyExporter",
            "",
            "import os",
        ]

        # Generate imports (immediately after import os)
        template_var_names = []
        for template in templates:
            name = template.name
            var_name = f"template_{name}"
            template_var_names.append(var_name)
            lines.append(f"from .{name}.template_{name} import {var_name}")

        lines.append("")
        lines.append("# Get current file directory")
        lines.append("_CURRENT_DIR = os.path.dirname(os.path.abspath(__file__))")
        lines.append("")
        lines.append("# " + "-" * 60)
        lines.append("# Templates registry")
        lines.append("# " + "-" * 60)
        lines.append("")
        lines.append("ALL_TEMPLATES = [")
        for var_name in template_var_names:
            lines.append(f"    {var_name},")
        lines.append("]")
        lines.append("")

        # Helper functions
        lines.extend([
            "",
            "# " + "-" * 60,
            "# Helper load functions",
            "# " + "-" * 60,
            "",
            "def load_global_declaration() -> str:",
            '    """Load global declaration."""',
            '    path = os.path.join(_CURRENT_DIR, "decl", "decl.txt")',
            '    with open(path, "r", encoding="utf-8") as f:',
            "        return f.read()",
            "",
            "",
            "def load_system_declaration() -> str:",
            '    """Load system declaration."""',
            '    path = os.path.join(_CURRENT_DIR, "sys_decl", "sys_decl.txt")',
            '    with open(path, "r", encoding="utf-8") as f:',
            "        return f.read()",
            "",
            "",
            "def load_queries() -> list:",
            '    """Load query list."""',
            "    from .queries.queries import QUERIES",
            "    return QUERIES",
            "",
        ])

        registry_path = os.path.join(output_dir, "registry.py")
        with open(registry_path, "w", encoding="utf-8") as f:
            f.write("\n".join(lines))

    @staticmethod
    def _escape_string(s: str) -> str:
        """Escape special characters in string for use in double-quoted strings.

        Args:
            s: String to escape.

        Returns:
            Escaped string safe for double quotes.
        """
        if s is None:
            return ""
        # Escape backslash first, then other special characters
        s = s.replace('\\', '\\\\')
        s = s.replace('"', '\\"')
        s = s.replace('\n', '\\n')
        s = s.replace('\r', '\\r')
        s = s.replace('\t', '\\t')
        return s

    @staticmethod
    def _escape_triple_quote_string(s: str) -> str:
        """Escape string for use inside triple quotes.

        Args:
            s: String to escape.

        Returns:
            Escaped string safe for triple quotes.
        """
        if s is None:
            return ""
        # Escape triple quotes within the string
        return s.replace('"""', '\\"\\"\\"')

    @staticmethod
    def _format_tuple(t: Tuple) -> str:
        """Format tuple as Python code.

        Args:
            t: Tuple to format.

        Returns:
            Python code string representation of tuple.
        """
        if t is None:
            return "None"
        return str(t)

    @staticmethod
    def _make_safe_identifier(name: str) -> str:
        """Convert a name to a safe Python identifier.

        Handles:
        - Names starting with numbers
        - Names containing special characters
        - Python reserved keywords

        Args:
            name: Original name.

        Returns:
            Safe Python identifier.
        """
        if not name:
            return "unnamed"

        # Replace special characters with underscore
        safe = re.sub(r'[^a-zA-Z0-9_]', '_', name)

        # If starts with number, prefix with underscore
        if safe[0].isdigit():
            safe = '_' + safe

        # If it's a Python keyword, prefix with underscore
        if keyword.iskeyword(safe):
            safe = safe + '_'

        return safe

    @staticmethod
    def _validate_template_names(templates: List["Template"]) -> None:
        """Validate all template names are legal for export.

        Checks:
        - Name matches [A-Za-z_][A-Za-z0-9_]* pattern
        - Name is not a Python keyword
        - Name is not a reserved directory name
        - All names are unique

        Args:
            templates: List of Template instances to validate.

        Raises:
            ValueError: If any template name is invalid.
        """
        seen_names = set()

        for template in templates:
            name = template.name

            # Check pattern
            if not VALID_NAME_PATTERN.match(name):
                raise ValueError(
                    f"Template name '{name}' is invalid. "
                    f"Must match pattern [A-Za-z_][A-Za-z0-9_]*"
                )

            # Check Python keyword
            if keyword.iskeyword(name):
                raise ValueError(
                    f"Template name '{name}' is a Python keyword and cannot be used."
                )

            # Check reserved names
            if name in RESERVED_NAMES:
                raise ValueError(
                    f"Template name '{name}' is reserved and cannot be used. "
                    f"Reserved names: {', '.join(sorted(RESERVED_NAMES))}"
                )

            # Check uniqueness
            if name in seen_names:
                raise ValueError(
                    f"Duplicate template name '{name}'. All template names must be unique."
                )
            seen_names.add(name)

    @staticmethod
    def _export_machine_mode(umodel: "UModel", output_dir: str) -> None:
        """Export in machine mode (TOML data format).

        Args:
            umodel: The UModel instance to export.
            output_dir: Output directory path.
        """
        # Export manifest.toml
        PyExporter._export_manifest_toml(umodel, output_dir)

        # Export decl.toml
        PyExporter._export_decl_toml(umodel.declaration, output_dir)

        # Export sys_decl.toml
        PyExporter._export_sys_decl_toml(umodel.system, output_dir)

        # Export queries.toml
        PyExporter._export_queries_toml(umodel.queries, output_dir)

        # Export each template to its own subdirectory
        for template in umodel.templates:
            PyExporter._export_template_toml(template, output_dir)

    @staticmethod
    def _export_manifest_toml(umodel: "UModel", output_dir: str) -> None:
        """Generate manifest.toml for machine mode.

        Args:
            umodel: The UModel instance.
            output_dir: Output directory path.
        """
        lines = [
            'format = "pyuppaal-pyfmt"',
            'format_version = 1',
            '',
            '[paths]',
            'decl = "decl/decl.toml"',
            'sys_decl = "sys_decl/sys_decl.toml"',
            'queries = "queries/queries.toml"',
            '',
        ]

        for template in umodel.templates:
            lines.append('[[templates]]')
            lines.append(f'name = "{template.name}"')
            lines.append(f'path = "{template.name}/{template.name}.toml"')
            lines.append('')

        manifest_path = os.path.join(output_dir, "manifest.toml")
        with open(manifest_path, "w", encoding="utf-8") as f:
            f.write("\n".join(lines))

    @staticmethod
    def _export_decl_toml(declaration: str, output_dir: str) -> None:
        """Generate decl/decl.toml for machine mode.

        Args:
            declaration: Global declaration content.
            output_dir: Output directory path.
        """
        # Create decl/ subdirectory
        decl_dir = os.path.join(output_dir, "decl")
        os.makedirs(decl_dir, exist_ok=True)

        content = declaration if declaration else ""
        escaped = PyExporter._escape_toml_multiline_string(content)

        lines = [
            f"declaration = '''{escaped}'''"
        ]

        decl_path = os.path.join(decl_dir, "decl.toml")
        with open(decl_path, "w", encoding="utf-8") as f:
            f.write("\n".join(lines) + "\n")

    @staticmethod
    def _export_sys_decl_toml(system: str, output_dir: str) -> None:
        """Generate sys_decl/sys_decl.toml for machine mode.

        Args:
            system: System declaration content.
            output_dir: Output directory path.
        """
        # Create sys_decl/ subdirectory
        sys_decl_dir = os.path.join(output_dir, "sys_decl")
        os.makedirs(sys_decl_dir, exist_ok=True)

        content = system if system else ""
        escaped = PyExporter._escape_toml_multiline_string(content)

        lines = [
            f"system = '''{escaped}'''"
        ]

        sys_decl_path = os.path.join(sys_decl_dir, "sys_decl.toml")
        with open(sys_decl_path, "w", encoding="utf-8") as f:
            f.write("\n".join(lines) + "\n")

    @staticmethod
    def _export_queries_toml(queries: List[str], output_dir: str) -> None:
        """Generate queries/queries.toml for machine mode.

        Args:
            queries: List of query strings.
            output_dir: Output directory path.
        """
        # Create queries/ subdirectory
        queries_dir = os.path.join(output_dir, "queries")
        os.makedirs(queries_dir, exist_ok=True)

        lines = ["queries = ["]

        if queries:
            for query in queries:
                if query is None:
                    continue
                escaped = PyExporter._escape_toml_basic_string(query)
                lines.append(f'  "{escaped}",')

        lines.append("]")

        queries_path = os.path.join(queries_dir, "queries.toml")
        with open(queries_path, "w", encoding="utf-8") as f:
            f.write("\n".join(lines) + "\n")

    @staticmethod
    def _export_template_toml(template: "Template", output_dir: str) -> None:
        """Generate {TemplateName}/{TemplateName}.toml for machine mode.

        Args:
            template: Template instance to export.
            output_dir: Output directory path.
        """
        name = template.name

        # Create {TemplateName}/ subdirectory
        template_dir = os.path.join(output_dir, name)
        os.makedirs(template_dir, exist_ok=True)

        # Build location_id to location_pos mapping for edge normalization
        loc_id_to_pos: Dict[int, Tuple[int, int]] = {}
        for loc in template.locations:
            loc_id_to_pos[loc.location_id] = loc.location_pos

        lines = [
            f'name = "{name}"',
            f'init_ref = {template.init_ref}',
        ]

        # Add params if present
        if template.params:
            escaped_params = PyExporter._escape_toml_basic_string(template.params)
            lines.append(f'params = "{escaped_params}"')

        lines.append('')

        # Add local declaration
        local_decl = template.declaration if template.declaration else ""
        escaped_decl = PyExporter._escape_toml_multiline_string(local_decl)
        lines.append(f"local_decl = '''{escaped_decl}'''")
        lines.append('')

        # Add locations
        lines.append('locations = [')
        for loc in template.locations:
            loc_line = PyExporter._format_location_toml(loc, template.init_ref)
            lines.append(f'  {loc_line},')
        lines.append(']')
        lines.append('')

        # Add edges
        lines.append('edges = [')
        if template.edges:
            for edge in template.edges:
                edge_lines = PyExporter._format_edge_toml(edge, loc_id_to_pos)
                for el in edge_lines:
                    lines.append(el)
        lines.append(']')

        template_path = os.path.join(template_dir, f"{name}.toml")
        with open(template_path, "w", encoding="utf-8") as f:
            f.write("\n".join(lines) + "\n")

    @staticmethod
    def _format_location_toml(location: "Location", init_ref: int) -> str:
        """Format a Location as TOML inline table.

        Args:
            location: Location instance.
            init_ref: Initial location reference ID.

        Returns:
            TOML inline table string.
        """
        parts = [
            f'id = {location.location_id}',
            f'pos = [{location.location_pos[0]}, {location.location_pos[1]}]',
        ]

        if location.name is not None:
            escaped = PyExporter._escape_toml_basic_string(location.name)
            parts.append(f'name = "{escaped}"')

        if location.name_pos is not None:
            parts.append(f'name_pos = [{location.name_pos[0]}, {location.name_pos[1]}]')

        if location.invariant is not None:
            escaped = PyExporter._escape_toml_basic_string(location.invariant)
            parts.append(f'invariant = "{escaped}"')

        if location.invariant_pos is not None:
            parts.append(f'invariant_pos = [{location.invariant_pos[0]}, {location.invariant_pos[1]}]')

        if location.rate_of_exponential is not None:
            parts.append(f'rate_of_exponential = {location.rate_of_exponential}')

        if location.rate_of_exp_pos is not None:
            parts.append(f'rate_of_exp_pos = [{location.rate_of_exp_pos[0]}, {location.rate_of_exp_pos[1]}]')

        # Use init_ref to determine if this is initial
        if location.location_id == init_ref:
            parts.append('is_initial = true')

        if location.is_urgent:
            parts.append('urgent = true')

        if location.is_committed:
            parts.append('committed = true')

        if location.is_branchpoint:
            parts.append('branchpoint = true')

        if location.comments is not None:
            escaped = PyExporter._escape_toml_basic_string(location.comments)
            parts.append(f'comments = "{escaped}"')

        if location.comments_pos is not None:
            parts.append(f'comments_pos = [{location.comments_pos[0]}, {location.comments_pos[1]}]')

        if location.test_code_on_enter is not None:
            escaped = PyExporter._escape_toml_basic_string(location.test_code_on_enter)
            parts.append(f'test_code_on_enter = "{escaped}"')

        if location.test_code_on_exit is not None:
            escaped = PyExporter._escape_toml_basic_string(location.test_code_on_exit)
            parts.append(f'test_code_on_exit = "{escaped}"')

        return '{ ' + ', '.join(parts) + ' }'

    @staticmethod
    def _format_edge_toml(edge: "Edge", loc_id_to_pos: Dict[int, Tuple[int, int]]) -> List[str]:
        """Format an Edge as TOML table.

        Args:
            edge: Edge instance.
            loc_id_to_pos: Mapping from location_id to location_pos.

        Returns:
            List of TOML lines for the edge.
        """
        # Normalize source/target positions to location positions
        source_pos = loc_id_to_pos.get(edge.source_location_id, edge.source_location_pos)
        target_pos = loc_id_to_pos.get(edge.target_location_id, edge.target_location_pos)

        lines = ['  {']
        lines.append(f'    source_id = {edge.source_location_id},')
        lines.append(f'    target_id = {edge.target_location_id},')
        lines.append(f'    source_pos = [{source_pos[0]}, {source_pos[1]}],')
        lines.append(f'    target_pos = [{target_pos[0]}, {target_pos[1]}],')

        if edge.select is not None:
            escaped = PyExporter._escape_toml_basic_string(edge.select)
            lines.append(f'    select = "{escaped}",')

        if edge.select_pos is not None:
            lines.append(f'    select_pos = [{edge.select_pos[0]}, {edge.select_pos[1]}],')

        if edge.sync is not None:
            escaped = PyExporter._escape_toml_basic_string(edge.sync)
            lines.append(f'    sync = "{escaped}",')

        if edge.sync_pos is not None:
            lines.append(f'    sync_pos = [{edge.sync_pos[0]}, {edge.sync_pos[1]}],')

        if edge.update is not None:
            escaped = PyExporter._escape_toml_basic_string(edge.update)
            lines.append(f'    update = "{escaped}",')

        if edge.update_pos is not None:
            lines.append(f'    update_pos = [{edge.update_pos[0]}, {edge.update_pos[1]}],')

        if edge.guard is not None:
            escaped = PyExporter._escape_toml_basic_string(edge.guard)
            lines.append(f'    guard = "{escaped}",')

        if edge.guard_pos is not None:
            lines.append(f'    guard_pos = [{edge.guard_pos[0]}, {edge.guard_pos[1]}],')

        if edge.probability_weight is not None:
            lines.append(f'    probability_weight = {edge.probability_weight},')

        if edge.prob_weight_pos is not None:
            lines.append(f'    prob_weight_pos = [{edge.prob_weight_pos[0]}, {edge.prob_weight_pos[1]}],')

        if edge.comments is not None:
            escaped = PyExporter._escape_toml_basic_string(edge.comments)
            lines.append(f'    comments = "{escaped}",')

        if edge.comments_pos is not None:
            lines.append(f'    comments_pos = [{edge.comments_pos[0]}, {edge.comments_pos[1]}],')

        if edge.test_code is not None:
            escaped = PyExporter._escape_toml_basic_string(edge.test_code)
            lines.append(f'    test_code = "{escaped}",')

        if edge.nails:
            nails_str = ', '.join(f'[{n[0]}, {n[1]}]' for n in edge.nails)
            lines.append(f'    nails = [{nails_str}],')

        lines.append('  },')
        return lines

    @staticmethod
    def _escape_toml_basic_string(s: str) -> str:
        """Escape string for use in TOML basic strings (double quotes).

        Args:
            s: String to escape.

        Returns:
            Escaped string safe for TOML basic strings.
        """
        if s is None:
            return ""
        # Escape backslash first, then other special characters
        s = s.replace('\\', '\\\\')
        s = s.replace('"', '\\"')
        s = s.replace('\n', '\\n')
        s = s.replace('\r', '\\r')
        s = s.replace('\t', '\\t')
        return s

    @staticmethod
    def _escape_toml_multiline_string(s: str) -> str:
        """Escape string for use in TOML multiline literal strings (triple quotes).

        Args:
            s: String to escape.

        Returns:
            Escaped string safe for TOML multiline literal strings.
        """
        if s is None:
            return ""
        # In TOML literal strings ('''), only ''' needs escaping
        # We escape by breaking the string
        return s.replace("'''", "'''\\''''")
